### ISSUE TITLE
Support Null Missions

### ISSUE THREAD

**Issue by JRascagneres** [TheSpaceDevs/.github#2]
@geoffreygarrett Looks like it doesn't handle null missions so is erroring currently. 
Can you take a look at all? I don't have great knowledge of the setup

**Comment by geoffreygarrett** [comment]
@JRascagneres currently travelling. I'll try get around to it Tuesday onwards. I'll also try bring over some updates I made to the setup which I developed on my profile.

**Comment by JRascagneres** [comment]
No worries. Looks like Nosu handled it :)
